# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab2_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EdgeDetector(object):
    def setupUi(self, EdgeDetector):
        EdgeDetector.setObjectName("EdgeDetector")
        EdgeDetector.resize(1080, 810)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EdgeDetector.sizePolicy().hasHeightForWidth())
        EdgeDetector.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(EdgeDetector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelOrig = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.labelOrig.sizePolicy().hasHeightForWidth())
        self.labelOrig.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.labelOrig.setFont(font)
        self.labelOrig.setFrameShape(QtWidgets.QFrame.Box)
        self.labelOrig.setText("")
        self.labelOrig.setObjectName("labelOrig")
        self.verticalLayout.addWidget(self.labelOrig)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButtonSelectImage = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelectImage.sizePolicy().hasHeightForWidth())
        self.pushButtonSelectImage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSelectImage.setFont(font)
        self.pushButtonSelectImage.setObjectName("pushButtonSelectImage")
        self.verticalLayout.addWidget(self.pushButtonSelectImage)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelSob = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.labelSob.setFont(font)
        self.labelSob.setFrameShape(QtWidgets.QFrame.Box)
        self.labelSob.setText("")
        self.labelSob.setObjectName("labelSob")
        self.verticalLayout_2.addWidget(self.labelSob)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.pushButtonDetectSobel = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDetectSobel.setFont(font)
        self.pushButtonDetectSobel.setObjectName("pushButtonDetectSobel")
        self.verticalLayout_2.addWidget(self.pushButtonDetectSobel)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelPrew = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.labelPrew.setFont(font)
        self.labelPrew.setFrameShape(QtWidgets.QFrame.Box)
        self.labelPrew.setText("")
        self.labelPrew.setObjectName("labelPrew")
        self.verticalLayout_3.addWidget(self.labelPrew)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.pushButtonDetectPrewitt = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDetectPrewitt.setFont(font)
        self.pushButtonDetectPrewitt.setObjectName("pushButtonDetectPrewitt")
        self.verticalLayout_3.addWidget(self.pushButtonDetectPrewitt)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelCannyCV = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.labelCannyCV.setFont(font)
        self.labelCannyCV.setFrameShape(QtWidgets.QFrame.Box)
        self.labelCannyCV.setText("")
        self.labelCannyCV.setObjectName("labelCannyCV")
        self.verticalLayout_6.addWidget(self.labelCannyCV)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_kernelCV = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_kernelCV.setObjectName("lineEdit_kernelCV")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_kernelCV)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_topthCV = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_topthCV.setClearButtonEnabled(False)
        self.lineEdit_topthCV.setObjectName("lineEdit_topthCV")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_topthCV)
        self.lineEdit_downthCV = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_downthCV.setObjectName("lineEdit_downthCV")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_downthCV)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.pushButtonDetectCannyCV = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDetectCannyCV.setFont(font)
        self.pushButtonDetectCannyCV.setObjectName("pushButtonDetectCannyCV")
        self.verticalLayout_6.addWidget(self.pushButtonDetectCannyCV)
        self.verticalLayout_6.setStretch(0, 8)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.setStretch(2, 1)
        self.verticalLayout_6.setStretch(3, 1)
        self.gridLayout.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelMatMorph = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.labelMatMorph.setFont(font)
        self.labelMatMorph.setFrameShape(QtWidgets.QFrame.Box)
        self.labelMatMorph.setText("")
        self.labelMatMorph.setObjectName("labelMatMorph")
        self.verticalLayout_4.addWidget(self.labelMatMorph)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.pushButtonDetectMatMorph = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDetectMatMorph.setFont(font)
        self.pushButtonDetectMatMorph.setObjectName("pushButtonDetectMatMorph")
        self.verticalLayout_4.addWidget(self.pushButtonDetectMatMorph)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelCanny = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.labelCanny.setFont(font)
        self.labelCanny.setFrameShape(QtWidgets.QFrame.Box)
        self.labelCanny.setText("")
        self.labelCanny.setObjectName("labelCanny")
        self.verticalLayout_5.addWidget(self.labelCanny)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_sigma = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_sigma.setObjectName("lineEdit_sigma")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sigma)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_topth = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_topth.setClearButtonEnabled(False)
        self.lineEdit_topth.setObjectName("lineEdit_topth")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_topth)
        self.lineEdit_downth = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_downth.setObjectName("lineEdit_downth")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_downth)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.pushButtonDetectCanny = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDetectCanny.setFont(font)
        self.pushButtonDetectCanny.setObjectName("pushButtonDetectCanny")
        self.verticalLayout_5.addWidget(self.pushButtonDetectCanny)
        self.verticalLayout_5.setStretch(0, 8)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.setStretch(3, 1)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        EdgeDetector.setCentralWidget(self.centralwidget)

        self.retranslateUi(EdgeDetector)
        QtCore.QMetaObject.connectSlotsByName(EdgeDetector)

    def retranslateUi(self, EdgeDetector):
        _translate = QtCore.QCoreApplication.translate
        EdgeDetector.setWindowTitle(_translate("EdgeDetector", "Edge Detector"))
        self.label_2.setText(_translate("EdgeDetector", "Исходное изображение"))
        self.pushButtonSelectImage.setText(_translate("EdgeDetector", "Выбрать изображение"))
        self.label_3.setText(_translate("EdgeDetector", "Метод Собеля"))
        self.pushButtonDetectSobel.setText(_translate("EdgeDetector", "Найти границы"))
        self.label_4.setText(_translate("EdgeDetector", "Метод Приютта"))
        self.pushButtonDetectPrewitt.setText(_translate("EdgeDetector", "Найти границы"))
        self.label_9.setText(_translate("EdgeDetector", "Метод Канни (OpenCV)"))
        self.label_10.setText(_translate("EdgeDetector", "Размер ядра"))
        self.lineEdit_kernelCV.setText(_translate("EdgeDetector", "5"))
        self.label_11.setText(_translate("EdgeDetector", "Верхний порог"))
        self.label_12.setText(_translate("EdgeDetector", "Нижний порог"))
        self.lineEdit_topthCV.setText(_translate("EdgeDetector", "2500"))
        self.lineEdit_downthCV.setText(_translate("EdgeDetector", "100"))
        self.pushButtonDetectCannyCV.setText(_translate("EdgeDetector", "Найти границы"))
        self.label_5.setText(_translate("EdgeDetector", "Метод математической морфологии"))
        self.pushButtonDetectMatMorph.setText(_translate("EdgeDetector", "Найти границы"))
        self.label_6.setText(_translate("EdgeDetector", "Метод Канни"))
        self.label.setText(_translate("EdgeDetector", "Сигма"))
        self.lineEdit_sigma.setText(_translate("EdgeDetector", "1.4"))
        self.label_7.setText(_translate("EdgeDetector", "Верхний порог"))
        self.label_8.setText(_translate("EdgeDetector", "Нижний порог"))
        self.lineEdit_topth.setText(_translate("EdgeDetector", "0.17"))
        self.lineEdit_downth.setText(_translate("EdgeDetector", "0.05"))
        self.pushButtonDetectCanny.setText(_translate("EdgeDetector", "Найти границы"))
